import { motion } from 'framer-motion';

export default function TermsOfService() {
  return (
    <div className="min-h-screen pt-24 pb-16">
      <div className="page-container max-w-3xl">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="glass-card border border-white/[0.06] p-8 sm:p-12">
          <h1 className="text-3xl font-serif text-gold-400 mb-6">Terms of Service</h1>
          <div className="space-y-6 text-white/70 leading-relaxed font-light text-sm">
            <p>Last updated: {new Date().toLocaleDateString()}</p>
            
            <section>
              <h2 className="text-lg text-white mb-2">1. Acceptance of Terms</h2>
              <p>By accessing and using Dharma Setu, you accept and agree to be bound by the terms and provision of this agreement.</p>
            </section>

            <section>
              <h2 className="text-lg text-white mb-2">2. Nature of Guidance</h2>
              <p>The spiritual guidance and reflections provided by Dharma Setu are generated by Artificial Intelligence. They are for educational, reflective, and entertainment purposes only. They should not be considered professional psychological, medical, or legal advice.</p>
            </section>

            <section>
              <h2 className="text-lg text-white mb-2">3. User Conduct</h2>
              <p>You agree to use the platform respectfully. Any abuse of the platform, including attempting to breach security or scrape data, will result in immediate termination of your account.</p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
